# This workflows will upload a Python Package using Twine when a release is created
# For more information see: https://help.github.com/en/actions/language-and-framework-guides/using-python-with-github-actions#publishing-to-package-registries

name: Build and upload Python Package

on:
  workflow_dispatch:
  release:
    types: [created]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.x'
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install setuptools wheel twine
    - name: Clean previous builds
      run: |
        rm -rf dist
    - name: Build package
      env:
        TWINE_USERNAME: ${{ secrets.PYPI_USERNAME }}
        TWINE_PASSWORD: ${{ secrets.PYPI_PASSWORD }}
      run: |
        python setup.py check
        python setup.py sdist bdist_wheel
    - name: Publish to pypi
      uses: pypa/gh-action-pypi-publish@v1.9.0
      with:
        # PyPI user
        user: ${{ secrets.PYPI_USERNAME }}
        password: ${{ secrets.PYPI_PASSWORD }}
        # Check metadata before uploading
        verify-metadata: true
        # Show verbose output.
        verbose: true
        # Show hash values of files to be uploaded
        print-hash: true
